name: flutter_qiita_client
description: A simple Qiita client application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  intl: ^0.16.1
  url_launcher: ^5.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.15.4

flutter:
  uses-material-design: true
